### ISSUE TITLE
build multiple definition problem

### ISSUE THREAD

**Issue by ofsahin** [halaei/lqrm#1]
hello,

this is a really old repo but i wanted to try the module and i get the following error while building.

a lot of lines like this:
/usr/bin/ld: CMakeFiles/laravelq.dir/src/laravel-release-reserved.c.o:(.bss+0x450): multiple definition of `RedisModule_SendClusterMessage'; CMakeFiles/laravelq.dir/src/blocking-pop.c.o:(.bss+0x450): first defined here

if you want to recreate the problem, here is my dockerfile:
```
FROM debian:11-slim as liblaravelq
RUN apt update && apt install -y git cmake
RUN cd /root && git clone https://github.com/halaei/lqrm && cd lqrm && mkdir build && cd build && cmake .. && make
```

**Comment by halaei** [comment]
Hello @ofsahin 
Thanks for your report.
Please take a look at the latest commit https://github.com/halaei/lqrm/commit/c0341e66e5b2d07f3eb0552c3b838a422d9e3bda and let me know if the issue still exists.

**Comment by ofsahin** [comment]
it worked. thank you
now i have to figure out how exactly this queue works
not much documentation available around
